workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: registry.speakeasyapi.dev/lukehagar/lukehagar/plex-api:main
targets:
    plexruby:
        target: ruby
        source: my-source
        publish:
            rubygems:
                token: $rubygems_auth_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/lukehagar/lukehagar/code-samples-ruby-plexruby
