workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    plexapi:
        inputs:
            - location: registry.speakeasyapi.dev/plexapi/plexapi/plexapi:main
targets:
    plexruby:
        target: ruby
        source: plexapi
        publish:
            rubygems:
                token: $rubygems_auth_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-ruby-plexruby
            labelOverride:
                fixedValue: PlexRuby
